sudo: required
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - "sudo apt-get install python3.5-dev dpkg-dev build-essential libwebkitgtk-dev libjpeg-dev libtiff-dev libgtk2.0-dev libsdl1.2-dev libgstreamer-plugins-base0.10-dev libnotify-dev freeglut3 freeglut3-dev python3-pip python3-setuptools"
  - "pip install -U --pre -f https://wxpython.org/Phoenix/snapshot-builds/ wxPython_Phoenix"
  - "pip install ObjectListView"
script: python3 $TARGET
